name: Action Sample

on:
  pull_request:

jobs:
  numpy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
      - name: Run Python
        run: python3 helloworld.py
     
      - name: build success
        if: success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: "問題なく実行できました"
        
      - name: build failure
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: "エラーが発生しました"
